Modules/Importantlink/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('importantlink')->group(function() {

//     Route::get('/', 'ImportantlinkController@index')->name('importantlink.index');
    
 //Route::get('importantlink/{edit}', 'ImportantlinkController@edit')->name('importantlink.edit');
    
//     Route::resource('operation', 'ImportantlinkController');
// });

Route::resource('importantlink','ImportantlinkController');

Modules/Importantlink/Entities/Importantlink.php
<?php

namespace Modules\Importantlink\Entities;

use Illuminate\Database\Eloquent\Model;

class Importantlink extends Model
{
    // protected $fillable = ['title','link','logo','active'];
    protected $guarded = ['id', 'created_at'];
}

Modules/Importantlink/Http/Controllers/ImportantlinkController.php
<?php

namespace Modules\Importantlink\Http\Controllers;

use Modules\Importantlink\Entities\Importantlink;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;

class ImportantlinkController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        abort_unless(\Gate::allows('importantsitelink_access'), 403);
        $importantlinks = Importantlink::all();
        return view('importantlink::index',compact('importantlinks'));
    }



    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        abort_unless(\Gate::allows('importantsitelink_create'), 403);
        return view('importantlink::create');
    }



    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'title' => 'required',
            'link' => 'required',
            'logo' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',

        ]);

        $data = $request->all();
        $data['created_by'] = Auth::id();
        if ($request->hasFile('logo')){ 
            $imageName = request()->logo->getClientOriginalName();

            request()->logo->move(public_path(trans('global.links.importantlink')), $imageName);

            $data['logo'] = $imageName;
        }

  
        $product = Importantlink::create($data);
        return redirect()->route('importantlink.index');
    }



    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit(Importantlink $importantlink)
    {
        // return $importantlink;
        abort_unless(\Gate::allows('importantsitelink_edit'), 403);
        return view('importantlink::edit',compact('importantlink'));
    }



    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request,Importantlink $importantlink)
    {
        //
        abort_unless(\Gate::allows('importantsitelink_edit'), 403);
        request()->validate([
            'title' => 'required',
            'link' => 'required',
            'logo' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);


        $data = $request->all(); 
        $data['updated_by'] = Auth::id();

        if( !($request->has('active')) ){
            $data['active'] = 0;            
        }

        if ($request->hasFile('logo')){ 
            if(file_exists(public_path(trans('global.links.importantlink')).$importantlink->logo))
            {
                unlink(public_path(trans('global.links.importantlink')).$importantlink->logo);
            }
            $imageName = request()->logo->getClientOriginalName();
            request()->logo->move(public_path('img/logo'), $imageName);
            $data['logo'] = $imageName;

        }

        $importantlink->update($data);
        // return redirect()->route('importantlink.index');
        if($importantlink){
            return redirect()->route('importantlink.index')->with('success', 'Update Successfull');
        }else {
            return redirect()->route('importantlink.index')->with('error', 'Not Update, Somtheing waswrong');
        }
    }




    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy(Importantlink $importantlink)
    {
        $importantlink->delete();
        return redirect()->route('importantlink.index');
    }

}

Modules/Importantlink/Resources/views/create.blade.php
@extends('layouts.admin')
@push('css')
<link href="{{ asset('css/aire.css') }}" rel="stylesheet" />
@endpush
@section('content')

<div class="card">
    <div class="card-header">
        Add Important link
    </div>

    <div class="card-body">

        {{ 
            Aire::open()
            ->route('importantlink.store')
            ->post()
            ->enctype('multipart/form-data')
            ->rules([
                'title' => ' ',
                'link' => 'url',
            ])->messages([
                'link' => 'Incorect link url'
            ])
        }}
        <div class="form-group">
            {{ Aire::input('input', 'Link Name:*')
              ->id('sample-input-field')
              ->name('title')
              ->placeholder('Site Name')
              ->value('')
              ->class('form-control mb-2') }}


            {{ Aire::input('input', 'Linr Url:*')
              ->id('link')
              ->name('link')
              ->placeholder('http://www.google.com')
              ->value('')
              ->class('form-control' )}}
              <label class="inline-block mb-2 font-semibold cursor-pointer text-base">Upload Logo:</label>
              <div class="form-inline">
                  <div class="form-group mb-2">
                     {{ Aire::file('logo')->id('filePhoto') }}
                  </div>
                  <div class="form-group mx-sm-3 mb-2">
                    <img id="previewHolder" alt="Uploaded Image Preview Holder" src="{{ asset('public/img/logo/006-jpg.png') }}" class="form-control" />
                  </div>
              </div>

            {{ Aire::submit('Create Link')->class('btn btn-success') }}

            <a class="btn btn-danger inline-block text-base rounded p-2 px-4 text-white bg-blue-600 border-blue-700 hover:bg-blue-700 hover:border-blue-900" href="{{ route('importantlink.index') }}">Cancel</a>
        </div>
        {{ Aire::close() }}
          
    </div>
</div>

@section('scripts')
@parent

<script type="text/javascript">
  function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function(e) {
      $('#previewHolder').attr('src', e.target.result);
    }

    reader.readAsDataURL(input.files[0]);
  }
}

$("#filePhoto").change(function() {
  readURL(this);
});
</script>
@endsection


@endsection

Modules/Importantlink/Resources/views/edit.blade.php
@extends('layouts.admin')
@push('css')
<link href="{{ asset('css/aire.css') }}" rel="stylesheet" />
@endpush
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} Add Important link
    </div>

    <div class="card-body">

        {{ 
            Aire::open()
            ->route('importantlink.update',$importantlink)
            ->enctype('multipart/form-data')
            ->bind($importantlink)
            ->rules([
                'title' => ' ',
                'link' => 'url'
            ])->messages([
                'link' => 'Incorect link url'
            ])
        }}
        <div class="form-group">
            {{ Aire::input('title', 'Link Name:*')
              ->id('title')
              ->placeholder('Site Name')
              ->required()
              ->value()
              ->class('form-control mb-2') }}


            {{ Aire::input('link', 'Linr Url:*')
              ->id('link')
              ->placeholder('http://www.google.com')
              ->required()
              ->class('form-control' )}}

              <label class="inline-block mb-2 font-semibold cursor-pointer text-base">Upload Logo:</label>
              <div class="form-inline">
                  <div class="form-group mb-2">
                    {{ Aire::file('logo')->id('filePhoto') }}
                  </div>
                  <div class="form-group mx-sm-3 mb-2">
                    <img id="previewHolder" alt="Uploaded Image Preview Holder" src="{{ $importantlink->logo ? asset(trans('global.links.importantlink').$importantlink->logo) : asset('public/img/logo/006-jpg.png') ?? '' }}" class="form-control" />
                  </div>
              </div>

            {{ Aire::checkbox('active', 'publish') }}

            {{ Aire::submit('Update Link')->class('btn btn-success') }}

            <a class="btn btn-danger inline-block text-base rounded p-2 px-4 text-white bg-blue-600 border-blue-700 hover:bg-blue-700 hover:border-blue-900" href="{{ route('importantlink.index') }}">cancel</a>

        </div>
        {{ Aire::close() }}
          
    </div>
</div>

@section('scripts')
@parent

<script type="text/javascript">
  function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function(e) {
      $('#previewHolder').attr('src', e.target.result);
    }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#filePhoto").change(function() {
    readURL(this);
  });
</script>
@endsection
@endsection

Modules/Importantlink/Resources/views/index.blade.php
@extends('layouts.admin')
@section('content')
@can('importantsitelink_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href='{{ route("importantlink.create") }}'>
                Add Important Link
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        Important Link List
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table id="example" class=" table table-bordered table-striped table-hover datatable text-center">
                <thead>
                    <tr>
                        <th>
                            
                        </th>
                        <th>
                            Site tittle
                        </th>
                        <th>
                            Link
                        </th>
                        <th>
                            logo
                        </th>
                        <th>
                            Publish
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($importantlinks as $key => $importantlink)
                        <tr data-entry-id="{{ $importantlink->id }}">
                            <td  width="1">
                                
                            </td>
                            <td>
                                {{ $importantlink->title ?? '' }}
                            </td>
                            <td width="5">
                                {{ $importantlink->link ?? '' }}
                            </td>
                            <td>
                                <img src="{{ $importantlink->logo ? asset(trans('global.links.importantlink').$importantlink->logo) : asset('public/img/logo/006-jpg.png') ?? '' }}" width="50" height="50">
                            </td>

                            <td>

                                {{ $importantlink->active ? 'Published' : 'Unpublish' ?? '' }}
                            </td>

                            <td>
                                @can('importantsitelink_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('importantlink.edit',$importantlink) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('importantsitelink_delete')
                                    <form action="{{ route('importantlink.destroy', $importantlink) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script>
    $(document).ready(function() {   
      let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
      $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    });
</script>
@endsection
@endsection