Modules/PhotoGallery/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->group(function() {

	Route::resource('photogallery', 'PhotoGalleryController');
	Route::resource('photogallery/album/uplode', 'PhotoGalleryController@imgs');
    /*Route::get('/', 'PhotoGalleryController@index');
    // Route::get('view/{id}', 'PhotoGalleryController@show')->name('show');
    Route::get('show/{id}',['as'=>'gallery.show','uses'=>'PhotoGalleryController@show']);*/

    Route::get('photogallery/album/{id}/uplode',['as'=>'photogallery.imgs','uses'=>'PhotoGalleryController@imgs']);
    Route::post('photogallery/album/uplode/image',['as'=>'photogallery.upload','uses'=>'PhotoGalleryController@uploadImages']);
});

Modules/PhotoGallery/Entities/Gallery.php
<?php

namespace Modules\PhotoGallery\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\News\Entities\News;
use Modules\PhotoGallery\Entities\Photos;

class Gallery extends Model
{
    protected $fillable = [];
    protected $guarded = ['id', 'created_at', 'updated_at'];

    public function news()
    {
        return $this->belongsTo(News::class);
    }

    public function photos()
    {
        // return $this->hasMany(Photos::class, 'gallery_idIndex', 'local_key');
        return $this->hasMany(Photos::class, 'gallery_id', 'id');
    }
}

Modules/PhotoGallery/Entities/Photos.php
<?php

namespace Modules\PhotoGallery\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\PhotoGallery\Entities\Gallery;

class Photos extends Model
{
    protected $fillable = [];
    protected $guarded = ['id', 'created_at', 'updated_at'];
}

Modules/PhotoGallery/Http/Controllers/PhotoGalleryController.php
<?php

namespace Modules\PhotoGallery\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use DB;
use Modules\PhotoGallery\Entities\Gallery;
use Modules\PhotoGallery\Entities\Photos;
// use Intervention\Image\Facades\Image;
use Image;

class PhotoGalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $album = Gallery::all();
        return view('photogallery::index', compact('album'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('photogallery::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request, Gallery $gallery)
    {
        //dd($request->all());
        abort_unless(\Gate::allows('photo_uplode'), 403);
        $validatedData = $request->validate([
            'title'=>'required',
            // 'photo'=>'required',
        ]);
        // dd(request()->all());
        $gallery = $request->all();
        $gallery['created_by'] = Auth::id();
        if ($request->hasFile('photo')){ 
            // $imageName = request()->logo->getClientOriginalName();
            $imageName = request()->input('name').'.'.request()->file('photo')->getClientOriginalExtension();
            request()->file('photo')->move(public_path(trans('global.links.gallery')), $imageName);
            $image = Image::make(public_path(trans('global.links.gallery').$imageName))->resize(450, 450);
            $image->save();

            $gallery['photo'] = $imageName;
        }
        $data = Gallery::create($gallery);
        $id = $data->id;
        if($data){
            return redirect()->route('photogallery.imgs',$id)->with('success', 'Album Create Successfull');
        }else {
            return redirect()->route('photogallery.index')->with('error', 'Not Created, Somtheing waswrong');
        }
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        // dd($id);
        $gallery = Gallery::find($id)->photos;
        // dd($gallery);
        return view('photogallery::view', compact('gallery','id'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        return view('photogallery::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
    public function imgs($id)
    {
        $gallery = Gallery::findOrFail($id);
        // dd($gallery);
        return view('photogallery::imgInput',compact('gallery'));
    }

    public function uploadImages(Request $request)
    {   
        abort_unless(\Gate::allows('photo_uplode'), 403);
        $imgName = now()->format('Y-m-d-H-i-s').'-'.request()->file->getClientOriginalName();
        $photos = new Photos();
        $photos->gallery_id  = request()->input('gallery');
        $photos->photo = $imgName;
        $photos->created_by = Auth::id();
        $photos->save();

        request()->file->move(public_path(trans('global.links.photo')), $imgName);
        return response()->json(['uploaded' => '/images/'.$imgName]);

    }
}

Modules/PhotoGallery/Resources/views/create.blade.php
@extends('layouts.admin')
@push('css')
<link href="{{ asset('css/aire.css') }}" rel="stylesheet" />
@endpush

@section('content')

@if(session()->get('msg'))
 <a href="{{route('news.index')}}" class="btn btn-success">Back to News List</a>

<div class="alert-success col-12 text-center h1 p-6  mt-5 mb-5">
    Successfully Create your "<i>News</i>". <br>If you want to add mode Photos, then click 
    <strong>
        <a href="{{ route('news.photoes',session()->get('msg')) }}">here</a>
    </strong> 
</div>

<div class="col text-center">
      <!-- <button class="btn btn-default">Centered button</button> -->
      <a href="{{ route('news.photoes',session()->get('msg')) }}" class="btn btn-danger btn-lg mt-6">Add More Photos</a>
</div>
@else
<!-- <script src="https://cdn.ckeditor.com/4.12.1/basic/ckeditor.js"></script> -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('photogallery.index')}}">Photo Gallery</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create New Album</li>
  </ol>
</nav>
<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} Album
    </div>

    <div class="card-body">
        {{ 
            Aire::open()
            ->route('photogallery.store')
            ->rules([
            'title' => 'required',
            'photo'=> 'required|file',
            ])
            ->messages([
            'title' => 'You must accept the terms',
            'photo' => 'Cover Photo is Rrequired',
            ]) 
            ->enctype('multipart/form-data')
        }}

        {{ 
            Aire::input()
            ->label('Title*')
            ->id('title')
            ->name('title')
            ->class('form-control') 
        }}


<img src="" id="cover-img-tag" width="200px" class="mb-2" />
        {{
            Aire::input()
            ->type('file')
            ->label('Album Cover Photo (image size must be 450 × 450) *')
            ->id('cover-photo')
            ->name('photo')
            
        }}



        {{ 
            Aire::button()
            ->labelHtml('<strong>Create Album</strong>')
            ->class('btn btn-danger')
            ->class('mt-2') 
        }}


        {{ Aire::close() }}
    </div>
</div>


<script src="{{ asset('js/js/http _ajax.googleapis.com_ajax_libs_jquery_1.9.1_jquery.js') }}"></script>

<script type="text/javascript">

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#cover-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#cover-photo").change(function(){
        readURL(this);
    });

</script>
@endif
@endsection

Modules/PhotoGallery/Resources/views/imgInput.blade.php
@extends('layouts.admin')


@section('styles')
<link href="{{ asset('Modules/News/Resources/assets/css/https _maxcdn.bootstrapcdn.com_bootstrap_4.0.0-beta_css_bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('Modules/News/Resources/assets/css/https _cdnjs.cloudflare.com_ajax_libs_bootstrap-fileinput_4.4.7_css_fileinput.css') }}" rel="stylesheet">
@endsection

@section('content')
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('photogallery.index')}}">Photo Gallery</a></li>
    <li class="breadcrumb-item"><a href="{{route('photogallery.show', $gallery->id)}}">{{$gallery->title}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Uplod Picture</li>
  </ol>
</nav>
<div class="card">
    <div class="card-header">
        Uplode To <b>{{$gallery->title}}</b>
    </div>

    <div class="card-body">
 <div class="container">
    
        <div class="row">
            <div class="col-md-12">
                <!-- <h1 class="text-center">$news->title</h1><br>                 -->
                    <div class="form-group">
                        <div class="file-loading">
                            <input id="image-file" type="file" name="file" accept="image/*" data-min-file-count="1" multiple>
                        </div>
                    </div>                
            </div>
        </div>
    </div>
</div>
@section('scripts')
	@parent
	<script src="{{ asset('Modules/News/Resources/assets/js/https _code.jquery.com_jquery-3.2.1.min.js') }}"></script>
	<script src="{{ asset('Modules/News/Resources/assets/js/https _cdnjs.cloudflare.com_ajax_libs_bootstrap-fileinput_4.4.7_js_fileinput.js') }}"></script>
	<script src="{{ asset('Modules/News/Resources/assets/js/https _cdnjs.cloudflare.com_ajax_libs_bootstrap-fileinput_4.4.7_themes_fa_theme.js') }}"></script>
	<script src="{{ asset('Modules/News/Resources/assets/js/https _cdnjs.cloudflare.com_ajax_libs_popper.js_1.11.0_umd_popper.min.js') }}"></script>
	<script src="{{ asset('Modules/News/Resources/assets/js/https _maxcdn.bootstrapcdn.com_bootstrap_4.0.0-beta_js_bootstrap.min.js') }}"></script>
    <script type="text/javascript">
        $("#image-file").fileinput({
            theme: 'fa',
            uploadUrl: "{{route('photogallery.upload')}}",
            uploadExtraData: function() {
                return {
                    _token: "{{ csrf_token() }}",
                    gallery: "{{$gallery->id}}",
                };
            },
            allowedFileExtensions: ['jpg', 'png', 'gif','jpeg'],
            overwriteInitial: false,
            maxFileSize:2048,
            maxFilesNum: 10
        });
    </script>
@endsection
@endsection

Modules/PhotoGallery/Resources/views/index.blade.php
@extends('layouts.admin')

@section('styles')
@parent
<link href="{{ asset('Modules/PhotoGallery/Resources/assets/css/jquery.bsPhotoGallery.css')}}" rel="stylesheet">
@endsection

@section('scripts')
@parent
<script src="{{ asset('Modules/PhotoGallery/Resources/assets/js/jquery.bsPhotoGallery.js')}}"></script>	
<script>
	$(document).ready(function(){
		$('ul.first').bsPhotoGallery({
			"classes" : "col-xl-3 col-lg-2 col-md-4 col-sm-4",
			"hasModal" : false,
			"shortText" : false  
		});
	});
</script>
@endsection

@section('content')
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Photo Gallery</li>
  </ol>
</nav>


    <nav class="navbar navbar-light bg-light justify-content-between">
      Photo Gallery
    @can('photo_uplode')
      <form class="form-inline">
        <a class="btn btn-outline-dark" href="{{ route('photogallery.create') }}">
          <i class="fas fa-edit nav-icon"></i>   Create Album
        </a>
      </form>
      @endcan
    </nav>

    <div class="card-body">
  	<div class="container">
  		<div>
  			<!-- Hedder -->
  		</div>
  		<ul class="row first">
  			@foreach ($album as $key => $gallery) 
  			<li>
  				<a href="{{ route('photogallery.show', $gallery->id) }}">
  					@if( ($gallery->title == NULL) && ($gallery->photo == NULL))
  					<img alt="Rocking the night away"  src="{{ asset(trans('global.links.news_show').$gallery->news->photo)}}">
  					<p>{{$gallery->news->title}}</p>
  					@else
  					<img alt="Rocking the night away"  src="{{ asset(trans('global.links.gallery_show').$gallery->photo)}}">
  					<p>{{$gallery->title}}</p>
  					@endif
  				</a>
  			</li>
  			@endforeach

  		</ul>
  	</div>
    </div> 
  @endsection

Modules/PhotoGallery/Resources/views/view.blade.php
@extends('layouts.admin')

@section('styles')
@parent
<link href="{{ asset('Modules/PhotoGallery/Resources/assets/css/jquery.bsPhotoGallery.css')}}" rel="stylesheet">
@endsection

@section('scripts')
@parent
<script src="{{ asset('Modules/PhotoGallery/Resources/assets/js/jquery.bsPhotoGallery.js')}}"></script>	
<script>
	$(document).ready(function(){
		$('ul.first').bsPhotoGallery({
			"classes" : "col-xl-3 col-lg-2 col-md-4 col-sm-4",
			"hasModal" : true,
			"shortText" : false  
		});
	});
</script>
@endsection

@section('content')
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('photogallery.index')}}">Photo Gallery</a></li>
    <li class="breadcrumb-item active" aria-current="page">Gallery Photoes</li>
  </ol>
</nav>
<div class="card">
    <nav class="navbar navbar-light bg-light justify-content-between">
      Photo Gallery
    @can('photo_uplode')
      <form class="form-inline">
        <a class="btn btn-outline-dark" href="{{ route('photogallery.imgs',$id) }}">
          <i class="fas fa-edit nav-icon"></i>   Add More Picture
        </a>
      </form>
      @endcan
    </nav>
        <div class="card-body">
  	<div class="container">
  		<div>
  			<!-- Hedder -->
  		</div>
  		<ul class="row first">
  			@foreach ($gallery as $key => $photo) 
        <li>    
            <img alt="Rocking the night away"  src="{{ asset(trans('global.links.photo_show').$photo->photo)}}">
            <!-- <p>photo->id</p> -->
        </li>
        @endforeach

  		</ul>
  	</div> 
  </div>
  </div>
  @endsection