Modules/Academic/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('admin/academic/category', 'view/category');
Route::prefix('admin')->group(function() {
    Route::resource('academic', 'AcademicController');
    Route::get('academic/download/{id}',[
        'as'=>'academic.download',
        'uses'=>'AcademicController@download'
    ]);



    Route::get('academic/view/category',[
        'as'=>'academic.catagory',
        'uses'=>'AcademicController@category'
    ]);
    // Route::get('academic/view/category',[
    //     'as'=>'academic.catagory',
    //     'uses'=>'AcademicController@category'
    // ]);
    Route::get('academic/category/create',[
        'as'=>'academic.catagory.create',
        'uses'=>'AcademicController@createCategoty'
    ]);
    Route::post('academic/category/store',[
        'as'=>'academic.category.store',
        'uses'=>'AcademicController@storecatagory'
    ]);
    Route::get('academic/category/{catagory}/edit',[
        'as'=>'academic.category.edit',
        'uses'=>'AcademicController@editcatagory'
    ]);
    Route::post('academic/category/update/{id}',[
        'as'=>'academic.category.update',
        'uses'=>'AcademicController@updatecatagory'
    ]);
    Route::delete('academic/category/delete/{id}',[
        'as'=>'academic.category.delete',
        'uses'=>'AcademicController@deletecatagory'
    ]);



    // });

});
    /*Route::get('/', 'AcademicController@index');
    Route::get('create',['as'=>'academic.create','uses'=>'AcademicController@create']);
    Route::get('show/{id}',['as'=>'academic.show','uses'=>'AcademicController@show']);
    Route::post('store',['as'=>'academic.store','uses'=>'AcademicController@store']);
    Route::post('update/{id}',['as'=>'academic.update','uses'=>'AcademicController@update']);
    Route::get('edit/{id}',['as'=>'academic.edit','uses'=>'AcademicController@edit']);
    Route::delete('delete/{id}',['as'=>'academic.delete','uses'=>'AcademicController@destroy']);
    */
    


    // Category Route
    // Route::prefix('academic')->group(function() {
    // Route::get('academic/category',[
    //     'as'=>'academic.category',
    //     'uses'=>'AcademicController@createCategoty'
    // ]);
    // Route::get('academic/category/list', 'AcademicController@category');

Modules/Academic/Resources/views/create.blade.php
@extends('layouts.admin')
@push('css')
<link href="{{ asset('css/aire.css') }}" rel="stylesheet" />
@endpush

@section('content')

@if(session()->get('msg'))
 <a href="{{url('academic')}}" class="btn btn-success">Back to Notice List</a>

<div class="alert-success col-12 text-center h1 p-6  mt-5 mb-5">
    "<i>Notice</i>"  Create Successfully
     
</div>

@else
<script src="https://cdn.ckeditor.com/4.12.1/basic/ckeditor.js"></script>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{url('academic')}}">Academic</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create Post</li>
  </ol>
</nav>
<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.academic.title_singular') }} {{ trans('global.academic.fields.post') }}
    </div>

    <div class="card-body">
        {{ 
            Aire::open()
            ->route('academic.store')
            ->rules([
            'title' => 'required',
            'discription' => 'required',
            'catagories_id' => 'required',
            'file'=> 'required|file',
            ])
            ->messages([
            'title' => 'You must accept the terms',
            'photo' => 'Cover Photo is Rrequired',
            ]) 
            ->enctype('multipart/form-data')
            ->method('POST')
        }}

        {{ 
            Aire::input()
            ->label('Title*')
            ->id('title')
            ->name('title')
            ->class('form-control') 
        }}

        {{ 
            Aire::textarea()
            ->label('Discription*')
            ->id('discription')
            ->name('discription')
            ->class('form-control') 
        }}

        <script>
            CKEDITOR.replace( 'discription' );
        </script>

        {{
            Aire::select($catagory)
            ->class('form-control')
            ->label('Post Catagory *')
            ->name('catagories_id')
            ->id('catagories_id')
            
        }}

        {{
            Aire::input()
            ->type('file')
            ->label('Post File*')
            ->id('file')
            ->name('file')
            
        }}


        {{ 
            Aire::button()
            ->labelHtml('<strong>Next</strong>')
            ->class('btn btn-danger')
            ->class('mt-2') 
        }}


        {{ Aire::close() }}
    </div>
</div>

@endif
@endsection

Modules/Academic/Resources/views/edit.blade.php
@extends('layouts.admin')
@push('css')
<link href="{{ asset('css/aire.css') }}" rel="stylesheet" />
@endpush

@section('content')

<script src="https://cdn.ckeditor.com/4.12.1/basic/ckeditor.js"></script>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('academic.index')}}">Academic</a></li>
    <li class="breadcrumb-item active" aria-current="page">Update</li>
  </ol>
</nav>
<div class="card">
    <div class="card-header">
        Edit Post
    </div>


    <div class="card-body">
    	{{ 
            Aire::open()
            ->route('academic.update',$academic)
            ->bind($academic)
            ->rules([
            'title' => 'required',
            'discription' => 'required',
            ])
            ->messages([
            'title' => 'You must input this fild',
            ]) 
            ->enctype('multipart/form-data')

        }}

        {{ 
            Aire::input()
            ->label('Title *')
            ->id('title')
            ->name('title')
            ->class('form-control') 
        }}

  
        {{ 
            Aire::textarea()
            ->label('Discription*')
            ->id('discription')
            ->name('discription')
            ->class('form-control')
        }}

        <script>
            CKEDITOR.replace( 'discription' );
        </script>

        {{ 
            Aire::button()
            ->labelHtml('<strong>Update</strong>')
            ->class('btn btn-danger')
            ->class('mt-2') 
        }}
        {{ Aire::close() }}
        
    </div>
</div>

@endsection

Modules/Academic/Resources/views/index.blade.php
@extends('layouts.admin')

@section('styles')
@parent

@endsection

@section('scripts')
@parent

@endsection

@section('content')
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Academic</li>
  </ol>
</nav>

<div class="card">


    <nav class="navbar navbar-light bg-light justify-content-between">
      {{ trans('global.academic.title_singular') }} {{ trans('global.academic.fields.post') }} {{ trans('global.list') }}
    @can('academic_create')
      <form class="form-inline">
        <a class="btn btn-outline-dark" href="{{ route("academic.create") }}">
          <i class="fas fa-edit nav-icon"></i>   {{ trans('global.add') }} {{ trans('global.academic.fields.post') }}
        </a>
      </form>
      @endcan
    </nav>

    <div class="card-body">
        <div class="table-responsive ">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10"></th>
                        <th>
                            {{ trans('global.academic.fields.post') }} {{ trans('global.academic.fields.title') }}
                        </th>
                        <th>
                            {{ trans('global.academic.fields.post') }} {{ trans('global.academic.fields.catagory') }}
                        </th>
                        <th>
                            {{ trans('global.academic.fields.post') }} {{ trans('global.academic.fields.file') }}
                        </th>
                        <th>
                            &nbsp;Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($academics as $key => $academic)
                        <tr data-entry-id="{{ $academic->id }}">
                            <td></td>
                            <td>
                                {{ $academic->title  }}
                            </td>
                            <td>
                                {{ $academic->category->title  }}
                            </td>
                            <td>
                                <a href="{{route('academic.download', $academic->id)}}">download</a>
                            </td>
                            <td>
                              @can('academic_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('academic.show', $academic) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                              @can('academic_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('academic.edit', $academic) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('academic_delete')
                                    <form action="{{ route('academic.destroy', $academic) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>
                            
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

Modules/Academic/Resources/views/show.blade.php
@extends('layouts.admin')
@section('style')
@parent
<!-- STYLE CSS -->
@endsection

@section('content')
<!-- body content -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('academic.index')}}">Academic</a></li>
    <li class="breadcrumb-item active" aria-current="page">view</li>
  </ol>
</nav>

<div class="card">
    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand"><b>Signle Post View</b></a>
      <form class="form-inline">
        <a class="form-control mr-sm-2" href="{{route('academic.edit', $academic)}}">
          <i class="fas fa-edit nav-icon"></i> Edit</a>
      </form>
    </nav>
  <div class="card-body">
    <p class="card-text"><h5 class="card-title">Notice Title: {{ $academic->title}}</h5></p>
    <p class="card-text"><h5>Categoty : {{ $academic->category->title}}</h5></p>
    <p class="card-text"><h5>Description:</h5>
      {!!  $academic->discription !!}
    </p>

  </div>
    
   </br>
   <div class="container mb-2">
    Attesment :  <a href="{{ route('academic.download', $academic->id) }}">{{ $academic->file}}</a>
   </div>
   <br>
</div>



@endsection