Modules/Homeslider/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('admin')->group(function() {
	Route::resource('homeslider','HomesliderController');
});

Modules/Homeslider/Entities/Homeslider.php
<?php

namespace Modules\Homeslider\Entities;

use Illuminate\Database\Eloquent\Model;

class Homeslider extends Model
{
    // protected $fillable = ['title','subtitle','image','active'];
    protected $guarded = ['id', 'created_at'];
}

Modules/Homeslider/Http/Controllers/HomesliderController.php
<?php

namespace Modules\Homeslider\Http\Controllers;

use Illuminate\{
    Http\Request,
    Http\Response,
    Routing\Controller
};
use Illuminate\Support\Facades\Auth;
// use Illuminate\Http\Response;
// use Illuminate\Routing\Controller;
use Modules\Homeslider\Entities\Homeslider;
use Intervention\Image\Facades\Image;
class HomesliderController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        abort_unless(\Gate::allows('homeslider_access'), 403);
        $homesliders = Homeslider::orderBy('active','ASC')->get();
        return view('homeslider::index',compact('homesliders'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        abort_unless(\Gate::allows('homeslider_create'), 403);
        return view('homeslider::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'title' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg',

        ]);

        $data = $request->all();
        $data['created_by'] = Auth::id();  
        if ($request->hasFile('image')){ 
            $imageName = now()->format('Y-m-d-H-i-s').'-'.request()->image->getClientOriginalName();
            request()->image->move(public_path(trans('global.links.homeslider')), $imageName);
            $data['image'] = $imageName;
            $image = Image::make(public_path(trans('global.links.homeslider')."{$imageName}"))->resize(1920, 750);
            $image->save();
        }

  
        $homeslider = Homeslider::create($data);

        if($homeslider){
            session()->put('success','Created successfully.');
        }else {
            session()->put('error','Not Create.');
        }
        return view('homeslider::create');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show(Homeslider $homeslider)
    {
        return view('homeslider::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit(Homeslider $homeslider)
    {
        abort_unless(\Gate::allows('homeslider_edit'), 403);
        $pub = Homeslider::where('active',1)->count();
        $unpub = Homeslider::where('active',0)->count();
        // return $pub." ".$unpub;
        return view('homeslider::edit',compact('homeslider','pub','unpub'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request,Homeslider $homeslider)
    {


        $data = $request->all();
        $data['updated_by'] = Auth::id();
        if( !($request->has('active')) ){
            $data['active'] = 0;            
        }
        elseif($request->has('active')){
            $count = Homeslider::where('active',1)->count();
            if($count >= 5){
                $data['active'] = 0;
                session()->put('publish','Only Support 5 image');
                return redirect()->route('homeslider.edit',compact('homeslider'));
            }
        }

        if ($request->hasFile('image')){
            // if($homeslider->image){
            //     unlink(public_path(trans('global.links.homeslider')).$homeslider->image);
            // }
            if(file_exists(public_path(trans('global.links.homeslider')).$homeslider->image))
            {
                unlink(public_path(trans('global.links.homeslider')).$homeslider->image);
            }
            $imageName = request()->image->getClientOriginalName();
            request()->image->move(public_path(trans('global.links.homeslider')), $imageName);
            $data['image'] = $imageName;
            $image = Image::make(public_path(trans('global.links.homeslider').$imageName))->resize(1920, 750);
            $image->save();
        }

        $homeslider->update($data);
        if($homeslider){
            return redirect()->route('homeslider.index')->with('success', 'Update Successfull');
        }else {
            return redirect()->route('homeslider.index')->with('error', 'Not Update, Somtheing waswrong');
        }
        // if($homeslider){
        //     session()->put('success','Updated successfully.');
        // }
        // return redirect()->route('homeslider.edit',compact('homeslider'));
    }




    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */

    public function destroy(Homeslider $homeslider)
    {
        // $homeslider->delete();
        // if($homeslider){
        //     session()->put('success','Deleted successfully.');
        // }
        // return redirect()->route('homeslider.index');

        $file= $homeslider->image;
        if($homeslider->delete())
        {
            $filename = public_path(trans('global.links.homeslider')).$file;
             if(\File::exists($filename)){
                 \File::delete($filename);
            }
           return redirect()->route('homeslider.index')->with('delete', 'Delete Successfull');
        }else {
            return redirect()->route('homeslider.index')->with('error', 'Not Deleted, Somtheing waswrong');
        }
    }
}

Modules/Homeslider/Resources/views/create.blade.php
@extends('layouts.admin')
@push('css')
<link href="{{ asset('css/aire.css') }}" rel="stylesheet" />
@endpush
@section('content')


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Administration</a></li>
    <li class="breadcrumb-item"><a href="#">Home Settings</a></li>
    <li class="breadcrumb-item"><a href="{{ route('homeslider.index') }}">Home Slider</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add New Image</li>
  </ol>
</nav>

<div class="card">
    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand"><b>Add New Social Link</b></a>

      @can('homeslider_create')
        <form class="form-inline">
          <a class="form-control mr-sm-2 btn btn-success" href="{{ route('homeslider.index') }}">Back</a>
        </form>
      @endcan

    </nav>

    <div class="card-body">

        {{ 
            Aire::open()
            ->route('homeslider.store')
            ->post()
            ->enctype('multipart/form-data')
            ->rules([
                'title' => 'required',
            ])
        }}
        <div class="form-group">
            {{ Aire::input('input', 'Slider Title:*')
              ->id('sample-input-field')
              ->name('title')
              ->placeholder('Site Name')
              ->value('')
              ->class('form-control mb-2') }}

            {{ Aire::input('input', 'Slider Sub-title:')
              ->id('sample-input-field')
              ->name('subtitle')
              ->placeholder('Site Name')
              ->value('')
              ->class('form-control mb-2') }}


              <label class="inline-block mb-2 font-semibold cursor-pointer text-base">Upload Image (image size must be 1920 × 750) * :</label>
              <div class="form-inline">
                  <div class="form-group mb-2">
                    {{ Aire::file('image')->id('filePhoto') }}
                  </div>
                  <div class="form-group mx-sm-3 mb-3 pb-3 pl-1 col-12">
                    <img id="previewHolder" alt="Uploaded Image Preview Holder" src="{{ asset('public/img/logo/006-jpg.png') }}" class="form-control" style="width: 50%;height: auto"/>
                  </div>
              </div>

            {{ Aire::submit('Save')->class('btn btn-success') }}

            <a class="btn btn-danger inline-block text-base rounded p-2 px-4 text-white bg-blue-600 border-blue-700 hover:bg-blue-700 hover:border-blue-900" href="{{ route('homeslider.index') }}">Cancel</a>
        </div>
        {{ Aire::close() }}
          
    </div>
</div>

@section('scripts')
@parent
<script src="{{ asset('public/lib/hullabaloo/js/hullabaloo.js') }}"></script>
<script type="text/javascript">
  function readURL(input) {
  if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function(e) {
        $('#previewHolder').attr('src', e.target.result);
      }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#filePhoto").change(function() {
    readURL(this);
  });

  var hulla = new hullabaloo();
  @if(Session::has('success')) 
          hulla.send("{{ Session::get('success') }}", 'success') 
     @php
       Session::forget('success');
     @endphp
  @endif
</script>
@endsection


@endsection

Modules/Homeslider/Resources/views/edit.blade.php
@extends('layouts.admin')
@push('css')
<link href="{{ asset('css/aire.css') }}" rel="stylesheet" />


@endpush
@section('content')

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Administration</a></li>
    <li class="breadcrumb-item"><a href="#">Home Settings</a></li>
    <li class="breadcrumb-item"><a href="{{ route('homeslider.index') }}">Home Slider</a></li>
    <li class="breadcrumb-item active" aria-current="page">Update New Image</li>
  </ol>
</nav>

<div class="card">

    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand"><b>Update Image</b></a>

      @can('homeslider_create')
        <form class="form-inline">
          <div class="btn btn-info mr-2">Total Image: {{ $pub+$unpub }}</div>
          <div class="btn btn-danger mr-2">Unpublished: {{ $unpub }}</div>
          <div class="btn btn-warning mr-5">Published: {{ $pub }}</div>
          <a class="form-control mr-sm-2 btn btn-success" href="{{ route('homeslider.index') }}">Back</a>
        </form>
      @endcan

    </nav>

    <div class="card-body">

        {{ 
            Aire::open()
            ->route('homeslider.update',$homeslider)
            ->enctype('multipart/form-data')
            ->bind($homeslider)
            ->rules([
                'title' => 'required'
            ])
        }}
        <div class="form-group">
            {{ Aire::input('input', 'Slider Title:')
              ->id('sample-input-field')
              ->name('title')
              ->placeholder('Site Name')
              ->class('form-control mb-2') }}

            {{ Aire::input('input', 'Slider Sub-title:')
              ->id('sample-input-field')
              ->name('subtitle')
              ->placeholder('Site Name')
              ->class('form-control mb-2') }}

              <label class="inline-block mb-2 font-semibold cursor-pointer text-base">Upload Image image size must be 1920 × 750) * :</label>
              <div class="form-inline">
                  <div class="form-group mb-2">
                    {{ Aire::file('image')->id('filePhoto') }}
                  </div>
                  <div class="form-group mx-sm-3 mb-2 col-12">
                    <img id="previewHolder" alt="Uploaded Image Preview Holder" src="{{ $homeslider->image ? asset(trans('global.links.homeslider_show').$homeslider->image) : asset('public/img/logo/006-jpg.png') ?? '' }}" class="form-control" style="width: 50%;height: auto"/>
                  </div>
              </div>
              
              
            {{ Aire::checkbox('active', 'publish') }}

            {{ Aire::submit('Update')->id('updateButton')->class('btn btn-success') }}

            <a id="Hello" class="success btn btn-danger inline-block text-base rounded p-2 px-4 text-white bg-blue-600 border-blue-700 hover:bg-blue-700 hover:border-blue-900" href="{{ route('homeslider.index') }}">cancel</a>

        </div>
        {{ Aire::close() }}
    </div>
</div>

@section('scripts')
@parent
<script src="{{ asset('public/lib/hullabaloo/js/hullabaloo.js') }}"></script>
<script type="text/javascript">
  var hulla = new hullabaloo();
  function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function(e) {
      $('#previewHolder').attr('src', e.target.result);
    }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#filePhoto").change(function() {
    readURL(this);
  });

  @if(Session::has('success')) 
          hulla.send("{{ Session::get('success') }}", 'success') 
     @php
       Session::forget('success');
     @endphp
  @endif


  @if(Session::has('publish')) 
          hulla.send("{{ Session::get('publish') }}", 'danger') 
     @php
       Session::forget('publish');
     @endphp
  @endif



</script>

@endsection
@endsection

Modules/Homeslider/Resources/views/index.blade.php
@extends('layouts.admin')
@section('content')


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Administration</a></li>
    <li class="breadcrumb-item"><a href="#">Home Settings</a></li>
    <li class="breadcrumb-item active" aria-current="page">Home Slider</li>
  </ol>
</nav>

<div class="card">
    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand"><b>All Social Links</b></a>

      @can('homeslider_create')
        <form class="form-inline">
          <div class="btn btn-xs btn-info mr-2">You can publish only 5 image for sliding</div>
          <a class="form-control mr-sm-2 btn btn-success" href="{{ route('homeslider.create') }}">Add Image</a>
        </form>
      @endcan

    </nav>

    <div class="card-body">
        <div class="table-responsive">
            <table id="example" class=" table table-bordered table-striped table-hover datatable text-center">
                <thead>
                    <tr>
                        <th>
                            
                        </th>
                        <th>
                            Slider Image
                        </th>
                        <th>
                            Slider Title
                        </th>
                        <th>
                            Sub Title
                        </th>
                        <th>
                            Publish
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($homesliders as $key => $homeslider)
                        <tr data-entry-id="{{ $homeslider->id }}">
                            <td>
                                
                            </td>

                            <td>
                                <img src="{{ $homeslider->image ? asset(trans('global.links.homeslider_show').$homeslider->image) : asset('public/img/logo/006-jpg.png') ?? '' }}" width="200" height="100">
                            </td>

                            <td>
                                {{ $homeslider->title ?? '' }}
                            </td>
                            <td>
                                {{ $homeslider->subtitle ?? '' }}
                            </td>

                            <td>

                                {{ $homeslider->active ? 'Published' : 'Unpublish' ?? '' }}
                            </td>

                            <td>
                                @can('homeslider_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('homeslider.edit',$homeslider) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('homeslider_delete')
                                    <form action="{{ route('homeslider.destroy', $homeslider) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script src="{{ asset('public/lib/hullabaloo/js/hullabaloo.js') }}"></script>
<script>
    $(document).ready(function() {   
      let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
      $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    });

    var hulla = new hullabaloo();
  @if(Session::has('success')) 
          hulla.send("{{ Session::get('success') }}", 'success') 
     @php
       Session::forget('success');
     @endphp
  @endif
  @if(Session::has('error')) 
          hulla.send("{{ Session::get('error') }}", 'danger') 
     @php
       Session::forget('error');
     @endphp
  @endif
</script>
@endsection
@endsection